version: '3.1'

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:dev"
    volumes:
      - /home/remco/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    depends_on:
      - mariadb
    
  mariadb:
    image: docker.io/mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: *******
    volumes:
      - /home/remco/mariadb:/var/lib/mysql

  adminer:
    container_name: adminer
    image: docker.io/adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  nginx:
    image: docker.io/jc21/nginx-proxy-manager:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      DB_MYSQL_HOST: *****
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: *****
      DB_MYSQL_PASSWORD: ******
      DB_MYSQL_NAME: ******
    volumes:
      - /home/remco/nginx:/data
      - /home/remco/nginx/letsencrypt:/etc/letsencrypt
  vaultwarden:
    restart: always
    container_name: vaultwarden
    image: docker.io/vaultwarden/server:latest
    volumes:
      - /home/remco/vaultwarden:/data/
    ports:
      - 8062:80
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Europe/Amsterdam
      - SUBDOMAINS=*******
      - TOKEN=*********
      - LOG_FILE=false #optional
    volumes:
      - /home/remco/duckdns/config:/config #optional
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /home/remco/deluge/config:/config
      - /home/remco/disk1/Downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - CLI_ARGS= #optional
    volumes:
      - /home/remco/duplicati/config>:/config
      - /home:/source
    ports:
      - 8200:8200
    restart: unless-stopped
   
  adguardhome:
    container_name: adguardhome
    restart: unless-stopped
    volumes:
        - /home/remco/adguard/adguard_data:/opt/adguardhome/work
        - /home/remco/adguard/adguard_config:/opt/adguardhome/conf
    ports:
        - '53:53/tcp'
        - '53:53/udp'
        - '3000:3000/tcp'
    image: adguard/adguardhome
